# Generated by Django 3.1.3 on 2020-12-09 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
